# Generated by Django 3.2.9 on 2022-05-03 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('national_id', models.CharField(max_length=80, unique=True, verbose_name='National id')),
                ('verification_digit', models.CharField(blank=True, max_length=3, null=True, verbose_name='Verification  digit')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
