# Generated by Django 3.2.9 on 2021-11-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('national_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='National id')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
