# Generated by Django 3.2.9 on 2021-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211129_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
    ]
