# Generated by Django 3.2.9 on 2021-11-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('display_order', 'last_name', 'first_name')},
        ),
    ]
